### ISSUE TITLE
Масштаб карты для парсинг окрестностей и городов-сателлитов

### ISSUE THREAD

**Issue by zeliboba7** [interlark/parser-2gis#26]
Приложение - пушка! Правда не нашел возможности задать масштаб в настройках, насколько я понимаю, сейчас браузер открывает карту города с какими-то окрестностями по умолчанию. От чего зависит масштаб (или увеличение) карты не очень понятно, но по умолчанию на карту не всегда входят окрестные населенные пункты и города-сателлиты, которых нет в списке. Можно попробовать изменить масштаб карты при уже запущенном парсере, иногда это срабатывает: сначала мне показывало 186 мест, после уменьшения уменьшения масштаба 802, сейчас парсится 382 место. Но при таком подходе иногда вылетает:
```
12/03/2023 15:15:22.637 | ERROR    | Ошибка во время работы парсера.
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/parser_2gis/runner/gui.py", line 69, in run
    self._parser.parse(writer)
  File "/home/user/.local/lib/python3.10/site-packages/parser_2gis/parser/parsers/main.py", line 208, in parse
    self._chrome_remote.perform_click(link)
  File "/home/user/.local/lib/python3.10/site-packages/parser_2gis/chrome/remote.py", line 356, in perform_click
    resolved_node = self._chrome_tab.DOM.resolveNode(backendNodeId=dom_node.backend_id)
  File "/home/user/.local/lib/python3.10/site-packages/pychrome/tab.py", line 177, in call_method
    raise CallMethodException("calling method: %s error: %s" % (_method, result['error']['message']))
pychrome.exceptions.CallMethodException: calling method: DOM.resolveNode error: Node with given id does not belong to the document
12/03/2023 15:15:22.643 | INFO     | Парсинг ссылки завершён.
12/03/2023 15:15:22.722 | INFO     | Удаление пустых колонок CSV.
12/03/2023 15:15:22.731 | INFO     | Удаление повторяющихся записей CSV.
12/03/2023 15:15:22.733 | INFO     | Парсинг завершён.

```
Можно ли как-то более контролируемо задать масштаб или увеличение в настройках? Насколько я понимаю, увеличение - это цифра после слэша в параметре `m` запроса, например, `https://2gis.ru/novosibirsk/search/аптеки?m=82.942781,55.017395/9`.

**Comment by zeliboba7** [comment]
Вопрос снят, по-видимому, указанная ошибка появляется только при уменьшении масштаба, когда следующее место находится за пределами карты. Кроме того, можно вручную добавить параметр `m` с указанием центра карты и ее масштаба, вроде бы работает. Может быть стоит добавить это в wiki?
