### ISSUE TITLE
Ошибка при запуске parser-2gis через докер контейнер

### ISSUE THREAD

**Issue by assylancode** [interlark/parser-2gis#30]
В докер установил google chrome, и версия все корректно показывает. Но при запуске парсинга разные ошибки выходить:
1)
Ошибка во время работы парсера.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/parser_2gis/runner/cli.py", line 29, in start
    parser.parse(writer)
  File "/usr/local/lib/python3.9/site-packages/parser_2gis/parser/parsers/main.py", line 196, in parse
    self._wait_requests_finished()
  File "/usr/local/lib/python3.9/site-packages/parser_2gis/common.py", line 64, in inner
    raise TimeoutError(func)
TimeoutError: <function MainParser._wait_requests_finished at 0x7f13c20e2c10>

Настроечные параметры передаю вот такие:

listUrls=['https://2gis.kz/taraz/search/%D0%90%D0%BF%D1%82%D0%B5%D0%BA%D0%B8']
binary_path=PosixPath('/usr/bin/google-chrome-stable') start_maximized=False headless=False disable_images=True silent_browser=True memory_limit=1400

Можно ли узнать в чем именно проблема?

parser-2gis запускаю через cli в python скрипт.:

![image](https://github.com/interlark/parser-2gis/assets/94607173/79be3024-48cf-491e-9a02-50586918e156)

**Comment by Eliac11** [comment]
жиза...
