### ISSUE TITLE
Удаление обработанных ссылок

### ISSUE THREAD

**Issue by Proteus86** [interlark/parser-2gis#4]
Иногда парсер падает в ошибку . 
И в принципе не понятно какие ссылки уже готовы какие нет . 
Было бы круто если обработанные ссылки удалялись из списка. 
И результат сохранялся .
Таким образом если даже парсер упал, то можно продолжить далее.

**Comment by Proteus86** [comment]
Ошибки парсера json. К сожалению не сохранил. Иначе добавил бы. Хорошо проявляется если в 2гис ходить с буржуйский ВПН

**Comment by Proteus86** [comment]
14:33:40.754 | Ошибка во время работы парсера.
Traceback (most recent call last):
  File "parser_2gis\gui\app.py", line 83, in run
  File "parser_2gis\parser\parser.py", line 200, in parse_url
  File "parser_2gis\common.py", line 58, in inner
  File "parser_2gis\chrome\remote.py", line 272, in get_response_body
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by interlark** [comment]
Хм, ок. Парсер вряд ли будет работать с нероссийских IP, это я узнал когда стал пускать тесты c раннерами в US - длительные тесты не проходили, т.к. антибот у 2GIS всячески боролся с подобной активностью. А с тестами из России всё работало на ура с любыми объемами и времязатратами.

Подобная ошибка странная и я её не учёл. Видимо, существует вероятность, что API endpoint 2GIS на обычный запрос может отдать невалидный или пустой документ, что вряд ли непредусмотренно документацией.

Эта ошибка получена с учётом использования российского или иностранного IP?

**Comment by interlark** [comment]
В [v0.1.6](https://github.com/interlark/parser-2gis/releases/tag/v0.1.6) исправлена обработка ответа сервера, который, оказывается, может выдать некорретный ответ.

Возможность удаления успешно завершённых ссылок из списка редактора ссылок в обработке.

**Comment by Proteus86** [comment]
Спасибо ! Запустил проверки с российским IP.
Есть еще странная ошибка . "Работа браузера прекращена". Но когда ее снова словлю отпишу в отдельную ошибку.
