### ISSUE TITLE
exception in decoder

### ISSUE THREAD

**Issue by hrz10p** [interlark/parser-2gis#50]
Exception in thread Thread-10:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "pychrome/tab.py", line 122, in _recv_loop
  File "json/__init__.py", line 357, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by interlark** [comment]
Исправлено в `v1.2.0`
