### ISSUE TITLE
превышено время ожидания

### ISSUE THREAD

**Issue by dtltd-kz** [interlark/parser-2gis#60]
Доброго времени суток.
выбираю 1 город, 1 рубрику. 
Выдает 
```
21:18:28.278 | Ошибка во время работы парсера.
Traceback (most recent call last):
  File "parser_2gis/runner/gui.py", line 63, in run
  File "parser_2gis/parser/factory.py", line 19, in get_parser
  File "parser_2gis/parser/parsers/main.py", line 44, in __init__
  File "parser_2gis/chrome/remote.py", line 69, in start
  File "parser_2gis/common.py", line 65, in inner
TimeoutError: <function ChromeRemote._connect_interface at 0x7f73dac354c0>
```
Kubuntu 24.04 Chrome  126.0.6478.126 (Официальная сборка), (64 бит)
В чем может быть причина?

**Comment by Kirill7mix** [comment]
Такая же ошибка, только у меня вроде из-за нехватки памяти

**Comment by kimashii-dan** [comment]
Привет, у тебя получилось решить эту проблему?

**Comment by Kirill7mix** [comment]
Привет, нет.

чт, 19 июн. 2025 г., 22:21 Dan ***@***.***>:
