### ISSUE TITLE
Ошибка во время работы парсера.

### ISSUE THREAD

**Issue by jorjik** [interlark/parser-2gis#62]
Traceback (most recent call last):
  File "parser_2gis\runner\gui.py", line 69, in run
  File "parser_2gis\parser\parsers\main.py", line 196, in parse
  File "parser_2gis\common.py", line 65, in inner
TimeoutError: <function MainParser._wait_requests_finished at 0x00000218397DB160>

**Comment by MishaCircle** [comment]
Такая же история под Win10 с любой ссылкой

16:52:29.300 | Ошибка во время работы парсера.
Traceback (most recent call last):
  File "parser_2gis\runner\gui.py", line 63, in run
  File "parser_2gis\parser\factory.py", line 19, in get_parser
  File "parser_2gis\parser\parsers\main.py", line 44, in __init__
  File "parser_2gis\chrome\remote.py", line 69, in start
  File "parser_2gis\common.py", line 65, in inner
TimeoutError: <function ChromeRemote._connect_interface at 0x0000022E84219160>

Он открывает окно браузера, но в нем ничего не происходит , судя по всему проблема с Хромом, но как фиксить я пока не разобрался

**Comment by jorjik** [comment]
> Такая же история под Win10 с любой ссылкой
> 
> 16:52:29.300 | Ошибка во время работы парсера. Traceback (most recent call last): File "parser_2gis\runner\gui.py", line 63, in run File "parser_2gis\parser\factory.py", line 19, in get_parser File "parser_2gis\parser\parsers\main.py", line 44, in **init** File "parser_2gis\chrome\remote.py", line 69, in start File "parser_2gis\common.py", line 65, in inner TimeoutError: <function ChromeRemote._connect_interface at 0x0000022E84219160>
> 
> Он открывает окно браузера, но в нем ничего не происходит , судя по всему проблема с Хромом, но как фиксить я пока не разобрался

я думаю на 2-Gis изменилась верстка, от этого ошибка...
