### ISSUE TITLE
Ошибка ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by Proteus86** [interlark/parser-2gis#8]
Во время работы получена ошибка . 
После нее парсер остановился. 
Получена ошибка при попытке запустить парсер очередной ссылки. 
Посути понятно откуда она растет . Это либо блокировка IP либо проблемы с инетом. 
Но желательно обрабатывать ошибку и перезапускать парсер ссылки . 

22:31:02.141 | Ошибка во время работы парсера.
Traceback (most recent call last):
  File "parser_2gis\gui\app.py", line 83, in run
  File "parser_2gis\parser\parser.py", line 138, in parse_url
  File "parser_2gis\chrome\remote.py", line 233, in navigate
parser_2gis.chrome.exceptions.ChromeException: net::ERR_CONNECTION_CLOSED

**Comment by interlark** [comment]
Насполько я понимаю, такая ошибка в браузере может произойти когда он пытается открыть интернет ресурс, но не может из-за проблем с интрнет-подключением.

![err_connection_closed-ne-udaetsya-poluchit-dostup](https://user-images.githubusercontent.com/20641837/177510758-d4007a66-59e0-459c-8f1c-09a8bb0609a4.jpg)

Можно попробовать сделать "Сброс сетевых параметров" или прописать "Авто DNS" как это описано [тут](https://mywebpc.ru/windows/err-connection-closed/).

Можно, конечно, отлавливать ошибки браузера парсером и пытаться снова его запустить, но изначальной проблемы с подключением это не решит. 

Как вариант можно добавить опцию перезапуска браузера при возникновении подобной ошибки, будет полезна если такие ошибки имеют стохастический характер.
